apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: kg-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kg-client
  template:
    metadata:
      labels:
        app: kg-client
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        env:
        - name: NEO4J_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-client-config
              key: neo4j_uri
        - name: NEO4J_USERNAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-client-config
              key: neo4j_username
        - name: NEO4J_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-client-config
              key: neo4j_password