services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
        - ./demo_data:/var/lib/neo4j/import
    environment:
        - NEO4J_AUTH=none
        - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8080:8080"

  client:
    build: 
      context: ./client
    container_name: kg-client
    environment:
      - NEO4J_URI=neo4j://neo4jexploration-neo4j-1:7687  
      - SERVER_URL=http://neo4jexploration-neo4j-1:7474  
    volumes:
      - ./data:/data
    depends_on:
      neo4j:
        condition: service_started


