services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8080:8080"
    networks:
      - kg-network

  client:
    build: 
      context: ./client
    container_name: kg-client
    environment:
      - NEO4J_URI=neo4j://neo4jexploration-neo4j-1:7687  # Updated container name
      - SERVER_URL=http://neo4jexploration-neo4j-1:7474  # Updated container name
    depends_on:
      neo4j:
        condition: service_started
    networks:
      - kg-network

networks:
  kg-network:
    name: kg-network
    external: true