services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_default__advertised__address=neo4j

      # APOC
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./data:/app/data
      - ./data:/import  # Mount data directory for imports

  server:
    build: 
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - PYTHONUNBUFFERED=1
    depends_on:
      - neo4j

  client:
    build:
      context: ./client
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/import  # Mount data directory
    depends_on:
      - neo4j
      - server

volumes:
  neo4j_data:
    external: false
  neo4j_logs:
    external: false
  neo4j_plugins:
    external: false