services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
        - ./demo_data:/var/lib/neo4j/import/demo_data
        - ./data:/var/lib/neo4j/import/data
        - ./import_data.sh:/var/lib/neo4j/import/import_data.sh
        - ./citations_header.csv:/var/lib/neo4j/import/citations_header.csv
        - ./sentences_header.csv:/var/lib/neo4j/import/sentences_header.csv
        - ./entities_header.csv:/var/lib/neo4j/import/entities_header.csv
        - ./predications_header.csv:/var/lib/neo4j/import/predications_header.csv
        - ./generic_concepts_header.csv:/var/lib/neo4j/import/generic_concepts_header.csv
    environment:
        # Existing configs
        - NEO4J_AUTH=none
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        - NEO4J_dbms_security_auth__enabled=false
        - NEO4J_PLUGINS=["apoc", "apoc-extended"]
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
        - NEO4J_dbms_security_procedures_unrestricted=apoc.*
        
        # Memory configurations
        - NEO4J_dbms_memory_heap_initial__size=16G
        - NEO4J_dbms_memory_heap_max__size=16G
        - NEO4J_dbms_memory_pagecache_size=8G
        
        # JVM settings for better performance
        - NEO4J_dbms_jvm_additional="-XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
        
        # Transaction and query settings for large operations
        - NEO4J_dbms_transaction_timeout=1h
        - NEO4J_dbms_transaction_state_max__size=0
        - NEO4J_dbms_memory_off__heap_max__size=8G
    
    deploy:
      resources:
        limits:
          memory: 28G
        reservations:
          memory: 24G
    
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8080:8080"
      
    command: >
      bash -c "
        set -e
        chmod +x /var/lib/neo4j/import/import_data.sh &&
        neo4j start &&
        tail -f /logs/neo4j.log
      "
    restart: unless-stopped
  # client:
  #   build: 
  #     context: ./client
  #   container_name: kg-client
  #   environment:
  #     - NEO4J_URI=neo4j://neo4jexploration-neo4j-1:7687  
  #     - SERVER_URL=http://neo4jexploration-neo4j-1:7474  
  #   volumes:
  #     - ./data:/data
  #   depends_on:
  #     neo4j:
  #       condition: service_started

