apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j-chart.fullname" . }}
  labels:
    {{- include "neo4j-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.neo4j.service.type }}
  ports:
    - port: {{ .Values.neo4j.service.browser.port }}
      targetPort: browser
      name: browser
    - port: {{ .Values.neo4j.service.bolt.port }}
      targetPort: bolt
      name: bolt
  selector:
    {{- include "neo4j-chart.selectorLabels" . | nindent 4 }}