server:
  image:
    repository: kg-server
    tag: latest
    pullPolicy: IfNotPresent
  
  neo4j:
    
    service:
      type: ClusterIP
      ports:
        browser: 7474
        bolt: 7687

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi