apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
  - port: 7474
    name: browser
    targetPort: 7474
  - port: 7687
    name: bolt
    targetPort: 7687
  type: LoadBalancer
