client:
  image:
    repository: kg-client
    tag: latest
    pullPolicy: IfNotPresent
  
  config:
    neo4jUri: "neo4j://kg-server:7687"
    neo4jUsername: neo4j
    neo4jPassword: yourpassword

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi